# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# Project
version=1.5.1
group=com.avalon.base
java_version=25

# Common
minecraft_version=26.3
mod_name=AvalonBase
mod_author=Huziyang520
mod_id=avalonbase
license=MIT
credits=
description=A shared support library providing GUI themes, a config framework and networking for other mods.
minecraft_version_range=[26.3, 26.4)
# NeoForm version used to remap the 'common' module for 26.3
neo_form_version=26.3-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.160.5+26.3
fabric_loader_version=0.19.5


neoforge_version=26.3.0.1-beta

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.installations.fromEnv=JAVA_HOME