
# Project
version=1.1.2
group=com.avalon.base
java_version=17

# Common
minecraft_version=1.19.2
mod_name=AvalonBase
mod_author=Huziyang520
mod_id=avalonbase
license=MIT
credits=
description=A shared support library mod providing GUI theme system, config framework and network framework for other mods. \nFeedback: https://github.com/Huziyang520/AvalonBase/issues or https://issue.mengcai.online/
minecraft_version_range=[1.19.2, 1.20)
# Parchment is intentionally omitted for 1.19.2 to avoid nonexistent version download failures.

# Fabric
fabric_version=0.76.0+1.19.2
fabric_loader_version=0.14.24

# Forge
forge_version=43.4.0
forge_loader_version_range=[43,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
