# Project
version=1.2.0
group=com.avalon.base
$121

# Common
$11.21.5
mod_name=AvalonBase
mod_author=Huziyang520
mod_id=avalonbase
license=MIT
credits=
description=A shared support library mod providing GUI theme system, config framework and network framework for other mods. \nFeedback: https://github.com/Huziyang520/AvalonBase/issues or https://issue.mengcai.online/
minecraft_version_range=[1.21.2, 1.21.6)
# NeoForm version used to remap the 'common' module for 1.21.1
#neo_form_version= TODO 按目标 MC 核定（MDG 可自动解析）
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
$10.128.2+1.21.5
$10.16.9

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
$121.5.98
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false